from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from nettwin.preflight_engine import PreflightResult
from nettwin.preflight_engine import run_preflight as _engine_run_preflight


def _redact_addresses(payload: dict[str, Any]) -> None:
    for row in payload.get("interface", {}).get("addresses", []):
        address = row.get("address")
        if address:
            row["address_sha256"] = hashlib.sha256(
                str(address).encode("utf-8")
            ).hexdigest()
        row["address"] = None
        row["netmask"] = None
    payload.get("interface", {})["local_addresses_redacted"] = True


def run_preflight(*args: Any, redact_local_addresses: bool = False, **kwargs: Any) -> PreflightResult:
    """User-facing preflight wrapper.

    Gateway detection may require the real local IPv4 on Windows. Therefore
    the engine first observes the local interface without redaction, then this
    wrapper removes local addresses before the artifact is returned/written.
    No network traffic is generated by this process.
    """
    try:
        result = _engine_run_preflight(
            *args,
            redact_local_addresses=False,
            **kwargs,
        )
    except OSError as exc:
        raise ValueError(f"No se pudo preparar la salida del preflight: {exc}") from exc

    if not redact_local_addresses:
        return result

    _redact_addresses(result.payload)
    result.output_path.write_text(
        json.dumps(result.payload, ensure_ascii=False, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    return result
